version: '3'
services:
  us_west:
    build: ./wc3inside/
    environment:
      WC3I_GATEWAY: Lordaeron
      WC3I_HOSTNAME: ${WC3I_HOSTNAME}
      WC3I_USERNAME: ${WC3I_USERNAME}
      WC3I_PASSWORD: ${WC3I_PASSWORD}
      CMD: wc3inside-parser
  us_east:
    build: ./wc3inside/
    environment:
      WC3I_GATEWAY: Azeroth
      WC3I_HOSTNAME: ${WC3I_HOSTNAME}
      WC3I_USERNAME: ${WC3I_USERNAME}
      WC3I_PASSWORD: ${WC3I_PASSWORD}
      CMD: wc3inside-parser
  europe:
    build: ./wc3inside/
    environment:
      WC3I_GATEWAY: Northrend
      WC3I_HOSTNAME: ${WC3I_HOSTNAME}
      WC3I_USERNAME: ${WC3I_USERNAME}
      WC3I_PASSWORD: ${WC3I_PASSWORD}
      CMD: wc3inside-parser
  webui:
    build: ./wc3inside/
    environment:
      WC3I_HOSTNAME: ${WC3I_HOSTNAME}
      WC3I_USERNAME: ${WC3I_USERNAME}
      WC3I_PASSWORD: ${WC3I_PASSWORD}
      CMD: wc3inside-server
    ports:
      - "80:8080"
  stats:
    build: ./wc3inside/
    environment:
      WC3I_HOSTNAME: ${WC3I_HOSTNAME}
      WC3I_USERNAME: ${WC3I_USERNAME}
      WC3I_PASSWORD: ${WC3I_PASSWORD}
      CMD: wc3inside-stats
  us_west_old:
    build: ./wc3inside/
    environment:
      WC3I_GATEWAY: Lordaeron
      WC3I_HOSTNAME: ${WC3I_HOSTNAME}
      WC3I_USERNAME: ${WC3I_USERNAME}
      WC3I_PASSWORD: ${WC3I_PASSWORD}
      CMD: wc3inside-parser --old
  us_east_old:
    build: ./wc3inside/
    environment:
      WC3I_GATEWAY: Azeroth
      WC3I_HOSTNAME: ${WC3I_HOSTNAME}
      WC3I_USERNAME: ${WC3I_USERNAME}
      WC3I_PASSWORD: ${WC3I_PASSWORD}
      CMD: wc3inside-parser --old
  europe_old:
    build: ./wc3inside/
    environment:
      WC3I_GATEWAY: Northrend
      WC3I_HOSTNAME: ${WC3I_HOSTNAME}
      WC3I_USERNAME: ${WC3I_USERNAME}
      WC3I_PASSWORD: ${WC3I_PASSWORD}
      CMD: wc3inside-parser --old
